### ISSUE TITLE
WishList

### ISSUE THREAD

**Issue by DifficultNick** [tiburon-research/vsc-xml-plugin#1]
**Общее**

- [ ] ~~Ui Autocomplete;~~
- [x] добавить возможные значения атрибутов;
- [x] сделать тему подсветки;
- [x] добавить DefinitionProvider для Methods;
- [ ] ~~зачать Diagnostic;~~
- [ ] ~~TibAutoCompleteItem: добавить Description/Documentation/Details ко всем;~~
- [x] добавить TibAutoComplete для CustomClasses;
- [x] добавить преобразования Item-Answer;
- [ ] ~~добавить простое преобразование текста в Answer/Item;~~
- [ ] ~~формирование ageList;~~
- [x] перегрузить Snippet для Redirect без Status;
- [x] подсветка [тегов];
- [x] создать правила форматирования для языка;
- [ ] ~~сделать переходы к Wiki (какой, нафиг, Wiki?);~~
- [ ] ~~snippet в виде Item*5;~~
- [x] предлагать Id существующих листов во все места, где они могут быть вставлены;
- [x] сделать возможность перехода к Page по Id;
- [x] changelog;
- [x] продумать подсветку [c#][/c#] во всех местах скрипта;
- [ ] ~~сделать возможность сохранять backup в той же папке;~~
- [x] сделать, чтобы `src=` предлагалось только внутри `(\[|<)img`;
- [x] закрывать теги при MultiSelection;
- [x]  сделать значения, которые подставляются по умолчанию в атрибутах, например, `Reset="true"`;
- [x] подсветка [c#] с `<![CDATA[` внутри;
- [ ] ~~AutoComplete для атрибутов [тегов];~~
- [x] подсветка `@ID/@Itera/@Var` и констант во всех местах кода;
- [ ] ~~definition для констант;~~
- [x] подставлять соответствующий snippet для Answer, внутри Repeat;
- [x] autocomplete для Methods;
- [ ] ~~исправлять первую букву на заглавную;~~
- [ ] ~~сохранять MixIds;~~
- [ ] ~~сделать для атрибутов массив исключающих;~~

**Comment by DifficultNick** [comment]
**Настройки**

- [ ] Минимальное количество символов, после которого появляется предложение AutoComplete;

**Comment by ornic** [comment]
- [ ] быстрая установка тэгов `[u]` / `[i]` / `[strong]` / etc вокруг выделенного текста.
- [ ] (опционально) форматирование текста между этими тэгами в соответствии со смыслом

**Comment by DifficultNick** [comment]
> добавить команды быстрой вставки всех имеющихся шаблонов, чтобы можно было любимые из них повесить на горячие клавиши


Вот тут написано, как это делается:
https://github.com/Microsoft/vscode/issues/17780

Список шаблонов будет в Readme #38
