### ISSUE TITLE
Сравнение версий

### ISSUE THREAD

**Issue by DifficultNick** [tiburon-research/vsc-xml-plugin#41]
Если будет API для получения последней залитой версии по пути к файлу скрипта, то можно сравнивать текущую версию с последней залитой.
Т.к. путь может использоваться для нескольких проектов, получать нужно данные в виде `[ProjectId:Text]`.

**Comment by ornic** [comment]
- API есть
- ждем https://github.com/tinchurin/survey.engine/issues/276
